name: Run Python Script Workflow

env:
  API_KEY: ${{ secrets.API_KEY }}
  SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello alex"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: print secret
        run: echo API_KEY
        shell: bash 



