name: Run Python Script

env:
  API_KEY: ${{ secrets.API_KEY }}
  SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello alex
        run: echo "hello alex"
        shell: bash

  goodbye:
        runs-on: ubuntu-latest
    steps:
      - name: print secret
        run: echo "secret"
        shell: bash 



